const info = 
    {
      school: ["Columbia College", "Fu Foundation School of Engineering and Applied Science", "School of General Studies",
       "Barnard College"],
      major: ["African American & African Diaspora Studies",
      "American Studies",
      "Ancient Studies",
      "Anthropology",
      "Applied Mathematics",
      "Applied Physics and Applied Mathematics	",
      "Archaeology",
      "Architecture",
      "Art History",
      "Art History & Visual Arts",
      "Astronomy",
      "Astrophysics",
      "Biochemistry",
      "Biology",
      "Biomedical Engineering",
      "Biophysics",
      "Chemical Engineering	",
      "Chemical Physics",
      "Chemistry",
      "Civil Engineering and Engineering Mechanics",
      "Classical Studies",
      "Classics",
      "Climate System Science",
      "Cognitive Science",
      "Comparative Literature and Society",
      "Computer Engineering	",
      "Computer Science",
      "Computer Science - Mathematics",
      "Creative Writing",
      "Dance",
      "Data Science",
      "Drama and Theatre Arts",
      "Earth & Environmental Engineering	",
      "Earth Science",
      "East Asian Studies",
      "Economics",
      "Economics - Mathematics",
      "Economics - Philosophy",
      "Economics - Political Science",
      "Economics - Statistics",
      "Electrical Engineering",
      "Engineering Mechanics	",
      "English",
      "Environmental Biology",
      "Environmental Chemistry",
      "Environmental Science",
      "Ethnicity and Race Studies",
      "Evolutionary Biology of the Human Species",
      "Film and Media Studies",
      "Financial Economics",
      "French",
      "French & Francophone Studies",
      "German Literature & Cultural History",
      "Hispanic Studies",
      "History",
      "History and Theory of Architecture",
      "Human Rights",
      "Industrial Engineering and Operations Research",
      "Information Science",
      "Italian",
      "Latin American and Caribbean Studies",
      "Linguistics",
      "Materials Science and Engineering	",
      "Mathematics",
      "Mathematics - Statistics",
      "Mechanical Engineering",
      "Medical Humanities",
      "Middle Eastern, South Asian & African Studies",
      "Music",
      "Neuroscience & Behavior",
      "Operations Research: Engineering Management Systems",
      "Operations Research: Financial Engineering",
      "Philosophy",
      "Physical Education",
      "Physics",
      "Political Science",
      "Political Science - Statistics",
      "Portuguese Studies",
      "Psychology",
      "Regional Studies",
      "Religion",
      "Russian Language & Culture",
      "Russian Literature & Culture",
      "Slavic (Non-Russian) Language and Culture",
      "Slavic Studies",
      "Sociology",
      "Statistics",
      "Sustainable Development",
      "Urban Studies",
      "Visual Arts",
      "Women's & Gender Studies",
      "Yiddish Studies"]
      
    };
  

  export default info;
  